=== kleag/syanot/test/Guide.ph2.dtd
<!ELEMENT DOCUMENT ( E+ ) >
<!ATTLIST DOCUMENT fichier NMTOKEN #REQUIRED >
<!ATTLIST DOCUMENT xmlns:xlink  CDATA      #FIXED "http://www.w3.org/1999/xlink">

<!ELEMENT E ( constituants,  relations ) >
<!ATTLIST E id NMTOKEN #REQUIRED >

<!ELEMENT F ( #PCDATA ) >
<!ATTLIST F id ID #REQUIRED >

<!ELEMENT Groupe ( F+ ) >
<!ATTLIST Groupe id ID #REQUIRED >
<!ATTLIST Groupe type ( GA | GN | GP | GR | NV | PV ) #REQUIRED >

<!ELEMENT a-propager EMPTY >
<!ATTLIST a-propager booleen ( faux | vrai ) #REQUIRED >


<!ELEMENT adjectif EMPTY >
<!ATTLIST adjectif	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST adjectif	  xlink:type (locator) #FIXED "locator">


<!ELEMENT adverbe EMPTY >
<!ATTLIST adverbe	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST adverbe	  xlink:type (locator) #FIXED "locator">


<!ELEMENT appose EMPTY >
<!ATTLIST appose	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST appose	  xlink:type (locator) #FIXED "locator">


<!ELEMENT attribut EMPTY >
<!ATTLIST attribut	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST attribut	  xlink:type (locator) #FIXED "locator">



<!ELEMENT auxiliaire EMPTY >
<!ATTLIST auxiliaire	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST auxiliaire	  xlink:type (locator) #FIXED "locator">



<!ELEMENT cod EMPTY >

<!ATTLIST cod	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST cod	  xlink:type (locator) #FIXED "locator">


<!ELEMENT complement EMPTY >

<!ATTLIST complement	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST complement	  xlink:type (locator) #FIXED "locator">


<!ELEMENT complementeur	EMPTY > 

<!ATTLIST complementeur   xlink:href      CDATA		  #IMPLIED>
<!ATTLIST complementeur    xlink:type (locator) #FIXED "locator">


<!ELEMENT constituants ( F | Groupe )+ >

<!ELEMENT coord-d EMPTY >

<!ATTLIST  coord-d	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  coord-d	  xlink:type (locator) #FIXED "locator">


<!ELEMENT coord-g EMPTY >

<!ATTLIST  coord-g	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  coord-g	  xlink:type (locator) #FIXED "locator">


<!ELEMENT coordonnant EMPTY >

<!ATTLIST  coordonnant	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  coordonnant	  xlink:type (locator) #FIXED "locator">



<!ELEMENT modifieur EMPTY >
<!ATTLIST  modifieur	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  modifieur	  xlink:type (locator) #FIXED "locator">


<!ELEMENT nom EMPTY >
<!ATTLIST  nom	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  nom	  xlink:type (locator) #FIXED "locator">

<!ELEMENT premier EMPTY >
<!ATTLIST  premier	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  premier	  xlink:type (locator) #FIXED "locator">


<!ELEMENT preposition EMPTY >
<!ATTLIST  preposition	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  preposition	  xlink:type (locator) #FIXED "locator">


<!ELEMENT relation ( a-propager | adjectif | adverbe | appose | attribut | auxiliaire | cod | complement | complementeur |coord-d | coord-g | coordonnant | modifieur | nom | premier | preposition | s-o | suivant | sujet | verbe )+ >
<!ATTLIST relation id ID #REQUIRED >
<!ATTLIST relation type ( APPOS | ATB-SO | AUX-V | COMP | COD-V | COORD | CPL-V | JUXT | MOD-A | MOD-N | MOD-P | MOD-R | MOD-V | SUJ-V ) #REQUIRED >
<!ATTLIST relation xlink:type (extended) #FIXED "extended" >

<!ELEMENT relations ( relation* ) >

<!ELEMENT s-o EMPTY >
<!ATTLIST s-o  valeur ( sujet | objet | ind ) #REQUIRED >


<!ELEMENT suivant EMPTY >
<!ATTLIST  suivant	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  suivant	  xlink:type (locator) #FIXED "locator">

<!ELEMENT sujet EMPTY >
<!ATTLIST  sujet	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  sujet	  xlink:type (locator) #FIXED "locator">

<!ELEMENT verbe EMPTY >

<!ATTLIST  verbe	  xlink:href      CDATA           #IMPLIED>
<!ATTLIST  verbe	  xlink:type (locator) #FIXED "locator">

=== kleag/syanot/test/essai.easy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DOCUMENT SYSTEM "Guide.ph2.dtd">
<DOCUMENT fichier="/home/anne/EASY/CorpusGuide/Relations/Guide.1.ph2.IR.xml" xmlns:xlink="http://www.w3.org/1999/xlink">
<E id="E1">
<Groupe type="3" id="E1G1">
 <F id="E1F1">En</F>
 <F id="E1F2">quelle</F>
 <F id="E1F3">année</F>
</Groupe>
<Groupe type="2" id="E1G2">
 <F id="E1F4">Desmond</F>
 <F id="E1F5">Mpilo</F>
 <F id="E1F6">Tutu</F>
</Groupe>
<Groupe type="5" id="E1G3">
 <F id="E1F7">a</F>
 <F id="E1F8">-t-il</F>
</Groupe>
<Groupe type="5" id="E1G4">
 <F id="E1F9">reçu</F>
</Groupe>
<Groupe type="2" id="E1G5">
 <F id="E1F10">le</F>
 <F id="E1F11">prix</F>
</Groupe>
<Groupe type="2" id="E1G6">
 <F id="E1F12">Nobel</F>
</Groupe>
<Groupe type="3" id="E1G7">
 <F id="E1F13">de</F>
 <F id="E1F14">la</F>
 <F id="E1F15">paix</F>
</Groupe>
 <F id="E1F16">?</F>
<relation xlink:type="extended" type="SUJ-V" id="E1R1">
<sujet xlink:type="locator" xlink:href="E1F6"/>
<verbe xlink:type="locator" xlink:href="E1F7"/>
</relation>
</E>
<E id="E2">
<Groupe type="3" id="E2G1">
 <F id="E2F1">En</F>
 <F id="E2F2">quelle</F>
 <F id="E2F3">année</F>
</Groupe>
<Groupe type="5" id="E2G2">
 <F id="E2F4">a</F>
 <F id="E2F5">-t-on</F>
</Groupe>
<Groupe type="4" id="E2G3">
 <F id="E2F6">vraiment</F>
</Groupe>
<Groupe type="5" id="E2G4">
 <F id="E2F7">construit</F>
</Groupe>
<Groupe type="2" id="E2G5">
 <F id="E2F8">la</F>
 <F id="E2F9">première</F>
 <F id="E2F10">automobile</F>
</Groupe>
 <F id="E2F11">?</F>
</E>
<E id="E3">
<Groupe type="2" id="E3G1">
 <F id="E3F1">Quelle</F>
 <F id="E3F2">jolie</F>
 <F id="E3F3">fille</F>
</Groupe>
 <F id="E3F4">!</F>
</E>
<E id="E4">
<Groupe type="2" id="E4G1">
 <F id="E4F1">Le</F>
 <F id="E4F2">journal</F>
</Groupe>
 <F id="E4F3">,</F>
<Groupe type="2" id="E4G2">
 <F id="E4F4">Simon</F>
 <F id="E4F5">Tivolle</F>
</Groupe>
 <F id="E4F6">.</F>
</E>
<E id="E5">
<Groupe type="2" id="E5G1">
 <F id="E5F1">Les</F>
 <F id="E5F2">trois</F>
 <F id="E5F3">jeunes</F>
 <F id="E5F4">filles</F>
</Groupe>
<Groupe type="5" id="E5G2">
 <F id="E5F5">ne</F>
 <F id="E5F6">l'</F>
 <F id="E5F7">ont</F>
</Groupe>
<Groupe type="4" id="E5G3">
 <F id="E5F8">pas</F>
</Groupe>
<Groupe type="5" id="E5G4">
 <F id="E5F9">admis</F>
</Groupe>
 <F id="E5F10">.</F>
</E>
<E id="E6">
<Groupe type="2" id="E6G1">
 <F id="E6F1">La</F>
 <F id="E6F2">porte</F>
</Groupe>
<Groupe type="3" id="E6G2">
 <F id="E6F3">de</F>
 <F id="E6F4">la</F>
 <F id="E6F5">chambre</F>
</Groupe>
<Groupe type="5" id="E6G3">
 <F id="E6F6">fermée</F>
</Groupe>
<Groupe type="3" id="E6G4">
 <F id="E6F7">à</F>
 <F id="E6F8">clef</F>
</Groupe>
<Groupe type="3" id="E6G5">
 <F id="E6F9">à</F>
 <F id="E6F10">l'</F>
 <F id="E6F11">intérieur</F>
</Groupe>
 <F id="E6F12">,</F>
<Groupe type="2" id="E6G6">
 <F id="E6F13">les</F>
 <F id="E6F14">volets</F>
</Groupe>
<Groupe type="3" id="E6G7">
 <F id="E6F15">de</F>
 <F id="E6F16">l'</F>
 <F id="E6F17">unique</F>
 <F id="E6F18">fenetre</F>
</Groupe>
<Groupe type="5" id="E6G8">
 <F id="E6F19">fermés</F>
</Groupe>
 <F id="E6F20">,</F>
<Groupe type="2" id="E6G9">
 <F id="E6F21">eux</F>
</Groupe>
<Groupe type="4" id="E6G10">
 <F id="E6F22">aussi</F>
</Groupe>
 <F id="E6F23">,</F>
<Groupe type="3" id="E6G11">
 <F id="E6F24">à</F>
 <F id="E6F25">l'</F>
 <F id="E6F26">intérieur</F>
</Groupe>
 <F id="E6F27">,</F>
 <F id="E6F28">et</F>
 <F id="E6F29">,</F>
<Groupe type="3" id="E6G12">
 <F id="E6F30">par-dessus</F>
 <F id="E6F31">les</F>
 <F id="E6F32">volets</F>
</Groupe>
 <F id="E6F33">,</F>
<Groupe type="2" id="E6G13">
 <F id="E6F34">les</F>
 <F id="E6F35">barreaux</F>
</Groupe>
<Groupe type="1" id="E6G14">
 <F id="E6F36">intacts</F>
</Groupe>
 <F id="E6F37">,</F>
<Groupe type="2" id="E6G15">
 <F id="E6F38">des</F>
 <F id="E6F39">barreaux</F>
</Groupe>
<Groupe type="3" id="E6G16">
 <F id="E6F40">à_travers</F>
 <F id="E6F41">lesquels</F>
</Groupe>
<Groupe type="5" id="E6G17">
 <F id="E6F42">vous</F>
 <F id="E6F43">n'</F>
 <F id="E6F44">auriez</F>
</Groupe>
<Groupe type="4" id="E6G18">
 <F id="E6F45">pas</F>
</Groupe>
<Groupe type="5" id="E6G19">
 <F id="E6F46">passé</F>
</Groupe>
<Groupe type="2" id="E6G20">
 <F id="E6F47">le</F>
 <F id="E6F48">bras</F>
</Groupe>
 <F id="E6F49">...</F>
 <F id="E6F50">et</F>
<Groupe type="2" id="E6G21">
 <F id="E6F51">mademoiselle</F>
</Groupe>
<Groupe type="2" id="E6G22">
 <F id="E6F52">qui</F>
</Groupe>
<Groupe type="5" id="E6G23">
 <F id="E6F53">appelait</F>
</Groupe>
<Groupe type="3" id="E6G24">
 <F id="E6F54">au</F>
 <F id="E6F55">secours</F>
</Groupe>
 <F id="E6F56">!</F>
 <F id="E6F57">...</F>
 <F id="E6F58">ou</F>
<Groupe type="4" id="E6G25">
 <F id="E6F59">plutêêêôt</F>
</Groupe>
<Groupe type="4" id="E6G26">
 <F id="E6F60">non</F>
</Groupe>
 <F id="E6F61">,</F>
<Groupe type="5" id="E6G27">
 <F id="E6F62">on</F>
 <F id="E6F63">ne</F>
 <F id="E6F64">l'</F>
 <F id="E6F65">entendait</F>
</Groupe>
<Groupe type="4" id="E6G28">
 <F id="E6F66">plus</F>
</Groupe>
 <F id="E6F67">...</F>
<Groupe type="5" id="E6G29">
 <F id="E6F68">elle</F>
 <F id="E6F69">était</F>
</Groupe>
<Groupe type="4" id="E6G30">
 <F id="E6F70">peut-etre</F>
</Groupe>
<Groupe type="1" id="E6G31">
 <F id="E6F71">morte</F>
</Groupe>
 <F id="E6F72">...</F>
 <F id="E6F73">mais</F>
<Groupe type="5" id="E6G32">
 <F id="E6F74">j'</F>
 <F id="E6F75">entendais</F>
</Groupe>
<Groupe type="4" id="E6G33">
 <F id="E6F76">encore</F>
</Groupe>
 <F id="E6F77">,</F>
<Groupe type="3" id="E6G34">
 <F id="E6F78">au</F>
 <F id="E6F79">fond</F>
</Groupe>
<Groupe type="3" id="E6G35">
 <F id="E6F80">du</F>
 <F id="E6F81">pavillon</F>
</Groupe>
 <F id="E6F82">,</F>
<Groupe type="2" id="E6G36">
 <F id="E6F83">monsieur</F>
</Groupe>
<Groupe type="2" id="E6G37">
 <F id="E6F84">qui</F>
</Groupe>
<Groupe type="5" id="E6G38">
 <F id="E6F85">essayait</F>
</Groupe>
<Groupe type="6" id="E6G39">
 <F id="E6F86">d'</F>
 <F id="E6F87">ébranler</F>
</Groupe>
<Groupe type="2" id="E6G40">
 <F id="E6F88">la</F>
 <F id="E6F89">porte</F>
</Groupe>
 <F id="E6F90">...</F>
<Groupe type="5" id="E6G41">
 <F id="E6F91">nous</F>
 <F id="E6F92">avons</F>
</Groupe>
<Groupe type="5" id="E6G42">
 <F id="E6F93">repris</F>
</Groupe>
<Groupe type="2" id="E6G43">
 <F id="E6F94">notre</F>
 <F id="E6F95">course</F>
</Groupe>
 <F id="E6F96">,</F>
<Groupe type="2" id="E6G44">
 <F id="E6F97">la</F>
 <F id="E6F98">concierge</F>
</Groupe>
 <F id="E6F99">et</F>
<Groupe type="2" id="E6G45">
 <F id="E6F100">moi</F>
</Groupe>
 <F id="E6F101">,</F>
 <F id="E6F102">et</F>
<Groupe type="5" id="E6G46">
 <F id="E6F103">nous</F>
 <F id="E6F104">sommes</F>
</Groupe>
<Groupe type="5" id="E6G47">
 <F id="E6F105">revenus</F>
</Groupe>
<Groupe type="3" id="E6G48">
 <F id="E6F106">au</F>
 <F id="E6F107">pavillon</F>
</Groupe>
 <F id="E6F108">.</F>
</E>
<E id="E7">
<Groupe type="2" id="E7G1">
 <F id="E7F1">Jean</F>
</Groupe>
<Groupe type="5" id="E7G2">
 <F id="E7F2">ne</F>
 <F id="E7F3">veut</F>
</Groupe>
<Groupe type="4" id="E7G3">
 <F id="E7F4">pas</F>
</Groupe>
<Groupe type="5" id="E7G4">
 <F id="E7F5">venir</F>
</Groupe>
 <F id="E7F6">.</F>
</E>
<E id="E8">
<Groupe type="2" id="E8G1">
 <F id="E8F1">Jean</F>
</Groupe>
<Groupe type="5" id="E8G2">
 <F id="E8F2">préfère</F>
</Groupe>
<Groupe type="5" id="E8G3">
 <F id="E8F3">ne_pas</F>
 <F id="E8F4">venir</F>
</Groupe>
 <F id="E8F5">.</F>
</E>
</DOCUMENT>
